INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "SUBARU");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "EUNOS");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MAZDA");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "SUZUKI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "FORD");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MITSUBISHI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MITSUOKA");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "ISUZU");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "BUICK");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "DODGE");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "PONTIAC");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "CADILLAC");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "SATURN");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "CHEVROLET");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "HUMMER");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "STARCRAFT");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "CHRYSLER");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "LINCOLN");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "TIRARA");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MERCURY");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MAYBACH");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "SAAB");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "AUDI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MCC SMART");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "VOLKSWAGEN");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "BMW");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MERCEDES BENZ");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "VOLVO");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MINI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "YES");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "DONKERVOORT");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "OPEL");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "PORSCHE");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "CITROEN");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "RENAULT");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "PEUGEOT");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "VENTURI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "ABARTH");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "FERRARI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "LANCIA");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "ALFA ROMEO");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "FIAT");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MASERATI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "AUTOBIANCHI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "LAMBORGHINI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "ASTON MARTIN");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "LAND ROVER");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "ROLLSROYCE");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "BENTLEY");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "LOTUS");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "ROVER");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "DAIMLER");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MG");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "TVR");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "JAGUAR");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "MORGAN");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "CT T");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "GM MATIZ");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "KIA");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "DAEWOO");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "HYUNDAI");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "BIRKIN");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "AMG");
INSERT INTO `car_make` (`id`, `make_name`) VALUES (NULL, "Lexus");